
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Nov 08 00:36:04 IST 2015
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int DIVIDE = 5;
  public static final int LCBR = 50;
  public static final int LTE = 35;
  public static final int INTEGER = 37;
  public static final int LPAREN = 6;
  public static final int SEMI = 16;
  public static final int CONTINUE = 23;
  public static final int INT = 36;
  public static final int MINUS = 8;
  public static final int STATIC = 18;
  public static final int RPAREN = 7;
  public static final int SEMICOLON = 2;
  public static final int LT = 34;
  public static final int LP = 48;
  public static final int COMMA = 17;
  public static final int CLASS = 12;
  public static final int RP = 49;
  public static final int PLUS = 3;
  public static final int MULTIPLY = 9;
  public static final int ASSIGN = 10;
  public static final int QUOTE = 20;
  public static final int IF = 27;
  public static final int THIS = 21;
  public static final int ID = 53;
  public static final int DOT = 26;
  public static final int EOF = 0;
  public static final int BOOLEAN = 11;
  public static final int RCBR = 51;
  public static final int LB = 46;
  public static final int LAND = 41;
  public static final int RETURN = 15;
  public static final int EQUAL = 43;
  public static final int TRUE = 29;
  public static final int NEW = 39;
  public static final int error = 1;
  public static final int RB = 47;
  public static final int LOR = 42;
  public static final int NULL = 31;
  public static final int NUMBER = 52;
  public static final int MOD = 45;
  public static final int BREAK = 24;
  public static final int VOID = 22;
  public static final int GTE = 33;
  public static final int TIMES = 4;
  public static final int ELSE = 28;
  public static final int WHILE = 25;
  public static final int NEQUAL = 44;
  public static final int CLASS_ID = 13;
  public static final int EXTENDS = 14;
  public static final int STRING = 19;
  public static final int LNEG = 40;
  public static final int FALSE = 30;
  public static final int GT = 32;
  public static final int LENGTH = 38;
}

