
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Nov 29 02:10:05 IST 2015
//----------------------------------------------------

package slp;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int DIVIDE = 7;
  public static final int LCBR = 35;
  public static final int LTE = 12;
  public static final int UMINUS = 2;
  public static final int INTEGER = 24;
  public static final int CONTINUE = 37;
  public static final int SEMI = 27;
  public static final int INT = 19;
  public static final int MINUS = 5;
  public static final int STATIC = 47;
  public static final int LT = 11;
  public static final int LP = 33;
  public static final int COMMA = 28;
  public static final int CLASS = 44;
  public static final int ELSE_OP = 3;
  public static final int RP = 34;
  public static final int PLUS = 4;
  public static final int MULTIPLY = 6;
  public static final int IF = 40;
  public static final int ASSIGN = 30;
  public static final int QUOTE = 23;
  public static final int THIS = 48;
  public static final int ID = 43;
  public static final int DOT = 29;
  public static final int EOF = 0;
  public static final int BOOLEAN = 21;
  public static final int RETURN = 46;
  public static final int RCBR = 36;
  public static final int LB = 31;
  public static final int LAND = 16;
  public static final int EQUAL = 13;
  public static final int TRUE = 26;
  public static final int NEW = 50;
  public static final int error = 1;
  public static final int RB = 32;
  public static final int LOR = 17;
  public static final int NULL = 22;
  public static final int MOD = 8;
  public static final int BREAK = 38;
  public static final int VOID = 18;
  public static final int GTE = 10;
  public static final int ELSE = 41;
  public static final int WHILE = 39;
  public static final int NEQUAL = 14;
  public static final int CLASS_ID = 42;
  public static final int EXTENDS = 45;
  public static final int STRING = 20;
  public static final int LNEG = 15;
  public static final int FALSE = 25;
  public static final int GT = 9;
  public static final int LENGTH = 49;
}

